/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.coders.hospital.view;

import com.coders.hospital.db.vo.UsersVo;

/**
 *
 * @author Codersbay
 */
public class Home extends javax.swing.JFrame {
    public static UsersVo usersVo;

    /**
     * Creates new form Home
     */
    public Home(UsersVo uv) {
        initComponents();
        this.setLocationRelativeTo(null);
        usersVo = uv;
        getUserLevel();
    }
    protected void getUserLevel(){
        switch(usersVo.getUsersType().getType()){
            case "admin":
                mDoctor.setEnabled(false);
                mNurse.setEnabled(false);
                mReception.setEnabled(false);
                break;

            case "doctor":
                mAdmin.setEnabled(false);
                mNurse.setEnabled(false);
                mReception.setEnabled(false);
                break;

            case "nurse":
                mDoctor.setEnabled(false);
                mAdmin.setEnabled(false);
                mReception.setEnabled(false);
                break;

            case "receptionist":
                mDoctor.setEnabled(false);
                mNurse.setEnabled(false);
                mAdmin.setEnabled(false);
                break;

            case "patient":
                break;

            case "pharmacist":
                break;

            case "laboratorist":
                break;

            case "acountant":
                break;

                
        } 
    }
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mAdmin = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mDoctor = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        mReception = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mNurse = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Codersbay\\Projects\\FinalProjects\\HospitalSystem\\images\\1.jpg")); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        mAdmin.setText("Admin");

        jMenuItem1.setText("Add New User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mAdmin.add(jMenuItem1);

        jMenuBar1.add(mAdmin);

        mDoctor.setText("Doctor");

        jMenuItem3.setText("Patient Info");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mDoctor.add(jMenuItem3);

        jMenuBar1.add(mDoctor);

        mReception.setText("Receptionist");

        jMenuItem2.setText("Patient Info");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mReception.add(jMenuItem2);

        jMenuBar1.add(mReception);

        mNurse.setText("Nurse");

        jMenuItem4.setText("Patient Info");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mNurse.add(jMenuItem4);

        jMenuBar1.add(mNurse);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        UsersView usersView =new UsersView();
        usersView.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

PatientInfoView patientInfoView =new PatientInfoView();
        patientInfoView.setVisible(true);



    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    MessageView messageView = new MessageView();
    messageView.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

MessageView messageView = new MessageView();
    messageView.setVisible(true);




    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //    new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu mAdmin;
    private javax.swing.JMenu mDoctor;
    private javax.swing.JMenu mNurse;
    private javax.swing.JMenu mReception;
    // End of variables declaration//GEN-END:variables
}
